apiVersion: apps/v1
kind: Deployment
metadata:
  name: concessionaria-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: concessionaria-service
  template:
    metadata:
      labels:
        app: concessionaria-service
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: concessionaria-service
          image: heitorramos123/concessionariaservice:latest
          ports:
            - containerPort: 8081
          env:
            - name: EUREKA_SERVER_URI
              value: "http://eureka-server:8761/eureka/"
---
apiVersion: v1
kind: Service
metadata:
  name: concessionaria-service
spec:
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
  selector:
    app: concessionaria-service